# Generated by Django 4.2.3 on 2023-08-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('course_app', '0004_chapter_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='问题内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_app.question', verbose_name='回答')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.section', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='提问者/回答者')),
            ],
            options={
                'db_table': 't_question',
            },
        ),
    ]
