# Generated by Django 4.2.3 on 2023-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_alter_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='问题标题'),
        ),
    ]
