### 获取个人订阅课程的名称列表
GET http://localhost:8000/api/user_courses_name/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE4NjAwMTEyMzQ2IiwiZXhwIjoxNjkyMzU5OTEyLjE0ODMyMzN9.s4gAShKAUIfzGo4sTRcOdAJgxPZAzg0g_aPjwZNjXpQ

### 获取个人订阅课程的列表
GET http://localhost:8000/api/user_courses_list/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE4NjAwMTEyMzQ2IiwiZXhwIjoxNjkyMzU5OTEyLjE0ODMyMzN9.s4gAShKAUIfzGo4sTRcOdAJgxPZAzg0g_aPjwZNjXpQ

### 获取个人收藏课程的列表
GET http://localhost:8000/api/user_sections_list/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE4NjAwMTEyMzQ2IiwiZXhwIjoxNjkyMzU5OTEyLjE0ODMyMzN9.s4gAShKAUIfzGo4sTRcOdAJgxPZAzg0g_aPjwZNjXpQ

### 增加个人收藏课程
POST http://localhost:8000/api/user_add_section/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE4NjAwMTEyMzQ2IiwiZXhwIjoxNjkyMzU5OTEyLjE0ODMyMzN9.s4gAShKAUIfzGo4sTRcOdAJgxPZAzg0g_aPjwZNjXpQ
Content-Type: application/json

{
    "section":71
}

### 获取个人订阅课程列表
GET http://localhost:8000/api/user_orders/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjE4NjAwMTEyMzQ2IiwiZXhwIjoxNjkyNzc0MzY2LjYxMDY2N30.Ezg8hN4Y-0LKCRzIZBmH3iiCVhqlNXgJKf4u4N7MZ0U