# Generated by Django 4.2.3 on 2023-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='t_teacher',
        ),
    ]
