# Generated by Django 4.2.3 on 2023-08-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecourse',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
