# Generated by Django 4.2.3 on 2023-08-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_app', '0005_classtype'),
        ('course_app', '0004_chapter_section'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_type', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='订单状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单金额')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际支付金额')),
                ('gmt_payment', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_app.classtype', verbose_name='班级类型')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
    ]
