# Generated by Django 4.2.3 on 2023-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='t_plan',
        ),
    ]
