# Generated by Django 4.2.3 on 2023-08-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_chapter_section'),
        ('plan_app', '0002_alter_plan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='course_app.course', verbose_name='课程'),
        ),
    ]
