# Generated by Django 4.2.3 on 2023-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0003_alter_plan_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='计划信息'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='计划介绍'),
        ),
    ]
