# Generated by Django 4.2.3 on 2023-08-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RotationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='轮播图名称')),
                ('img', models.CharField(max_length=255, verbose_name='轮播图图片')),
            ],
            options={
                'db_table': 't_rotation_chart',
            },
        ),
    ]
