# Generated by Django 4.2.3 on 2023-08-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='服务特色名称')),
            ],
            options={
                'db_table': 't_feature_service',
            },
        ),
    ]
