# Generated by Django 4.2.3 on 2023-08-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0004_chapter_section'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='course_app.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='user_app.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_user_course',
            },
        ),
    ]
