# Generated by Django 4.2.3 on 2023-08-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('course_app', '0004_chapter_section'),
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_section', to='course_app.section', verbose_name='课程小节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_section', to='user_app.user', verbose_name='用户')),
            ],
            options={
                'db_table': 't_user_section',
            },
        ),
    ]
