# Generated by Django 4.2.3 on 2023-08-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0004_chapter_section'),
        ('teacher_app', '0002_alter_teacher_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='价格')),
                ('img', models.CharField(blank=True, max_length=512, null=True, verbose_name='图片')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_courses', to='course_app.stage', verbose_name='课程阶段')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_courses', to='teacher_app.teacher', verbose_name='讲师')),
            ],
            options={
                'db_table': 't_free_course',
            },
        ),
    ]
