# Generated by Django 4.2.3 on 2023-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('_password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码2')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('job_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='职位')),
                ('introduction', models.CharField(blank=True, max_length=256, null=True, verbose_name='简介')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='头像')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
