# Generated by Django 4.2.3 on 2023-08-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='course_app.course', verbose_name='课程分类'),
        ),
    ]
