name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('bz_edu_project/requirments.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: bz_edu_project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Static analysis & Django checks
        env:
          DJANGO_SETTINGS_MODULE: bz_edu_project.settings_ci
        working-directory: bz_edu_project
        run: |
          python -m compileall .
          python manage.py check